# Import more components
external_components:
  - source: github://monorkin/esphome_st7565@main
    components: [ st7565 ]

# Project configuration
esphome:
  name: air-quality-box
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Quality-Box Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Configure I2C busses
i2c:
  - sda: D1
    scl: D2
    scan: true
    id: primary_i2c_bus

# Configure serial lines
uart:
  - rx_pin: D3
    tx_pin: D4
    baud_rate: 9600
    id: mhz19b_serial

# Configure SPI busses
spi:
  - clk_pin: D5
    mosi_pin: D6
    id: primary_spi_bus

# Import fonts
font:
  - file: "fonts/Roboto-Regular.ttf"
    id: my_font
    size: 15

# Setup displays
display:
  - platform: st7565
    spi_id: primary_spi_bus
    width: 128
    height: 64
    dc_pin:
      number: D8
    cs_pin:
      number: D7
    reset_pin:
      number: D0
    # rotation: 180
    lambda: |-
      it.print(0, 0, id(my_font), "ST7565");
      it.print(0, 20, id(my_font), "On ESPHome!");

# Configure sensors
sensor:
  - platform: bme680
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    gas_resistance:
      name: "Gas Resistance"
    i2c_id: primary_i2c_bus
    address: 0x77
    update_interval: 60s

  - platform: sps30
    pm_1_0:
      name: "Particulate Matter <1µm Weight concentration"
      id: "PM_1_0"
    pm_2_5:
      name: "Particulate Matter <2.5µm Weight concentration"
      id: "PM_2_5"
    pm_4_0:
      name: "Particulate Matter <4µm Weight concentration"
      id: "PM_4_0"
    pm_10_0:
      name: "Particulate Matter <10µm Weight concentration"
      id: "PM_10_0"
    pmc_0_5:
      name: "Particulate Matter <0.5µm Number concentration"
      id: "PMC_0_5"
    pmc_1_0:
      name: "Particulate Matter <1µm Number concentration"
      id: "PMC_1_0"
    pmc_2_5:
      name: "Particulate Matter <2.5µm Number concentration"
      id: "PMC_2_5"
    pmc_4_0:
      name: "Particulate Matter <4µm Number concentration"
      id: "PMC_4_0"
    pmc_10_0:
      name: "Particulate Matter <10µm Number concentration"
      id: "PMC_10_0"
    i2c_id: primary_i2c_bus
    address: 0x69
    update_interval: 120s

  - platform: mhz19
    co2:
      name: "CO2 Value"
    temperature:
      name: "CO2 Temperature"
      internal: true
    update_interval: 180s
    automatic_baseline_calibration: true
    uart_id: mhz19b_serial
