external_components:
  - source: github://monorkin/esphome_st7565@main
    components: [ st7565 ]

esphome:
  name: air-quality-box
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: "password"

ota:
  password: "password"

wifi:
  ssid: "foo"
  password: "bar"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Quality-Box Fallback Hotspot"
    password: "foobar"

captive_portal:

# Configure I2C busses
i2c:
  sda: D1
  scl: D2
  scan: true
  id: primary_bus

# Configure serial line for MH-Z19B
uart:
  rx_pin: D3
  tx_pin: D4
  baud_rate: 9600
  id: mhz19b_serial

spi:
  clk_pin: D5
  mosi_pin: D6

font:
  - file: "fonts/Roboto-Regular.ttf"
    id: my_font
    size: 20

display:
  - platform: st7565
    width: 128
    height: 64
    dc_pin:
      number: D8
    cs_pin:
      number: D7
    lambda: |-
      it.print(0, 0, id(my_font), "Hello World!");

# Configure sensors
sensor:
  - platform: bme680
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    gas_resistance:
      name: "Gas Resistance"
    address: 0x77
    update_interval: 60s
  - platform: sps30
    pm_1_0:
      name: "Particulate Matter <1µm Weight concentration"
      id: "PM_1_0"
    pm_2_5:
      name: "Particulate Matter <2.5µm Weight concentration"
      id: "PM_2_5"
    pm_4_0:
      name: "Particulate Matter <4µm Weight concentration"
      id: "PM_4_0"
    pm_10_0:
      name: "Particulate Matter <10µm Weight concentration"
      id: "PM_10_0"
    pmc_0_5:
      name: "Particulate Matter <0.5µm Number concentration"
      id: "PMC_0_5"
    pmc_1_0:
      name: "Particulate Matter <1µm Number concentration"
      id: "PMC_1_0"
    pmc_2_5:
      name: "Particulate Matter <2.5µm Number concentration"
      id: "PMC_2_5"
    pmc_4_0:
      name: "Particulate Matter <4µm Number concentration"
      id: "PMC_4_0"
    pmc_10_0:
      name: "Particulate Matter <10µm Number concentration"
      id: "PMC_10_0"
    address: 0x69
    update_interval: 60s
  - platform: mhz19
    co2:
      name: "CO2 Value"
    temperature:
      name: "CO2 Temperature"
      internal: true
    update_interval: 60s
    automatic_baseline_calibration: false
    uart_id: mhz19b_serial
